version: '3.7'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    command: ["ng","serve","--host","0.0.0.0"]
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    ports:
      - '4200:4200'
